DROP TABLE IF EXISTS WINDMILL_DETAILS;
  
CREATE TABLE WINDMILL_DETAILS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  uid VARCHAR(16) NOT NULL,
  name VARCHAR(50) NOT NULL,
  address VARCHAR(250) DEFAULT NULL,
  latitude VARCHAR(50) DEFAULT NULL,
  longitude VARCHAR(50) DEFAULT NULL
);

DROP TABLE IF EXISTS WINDMILL_POWER;
  
CREATE TABLE WINDMILL_POWER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  windmill_uid VARCHAR(16) NOT NULL,
  generated_date DATE NOT NULL,
  power INT DEFAULT NULL
);